### PR TITLE
feat: added `process_historical_summaries_update`

### LINKED ISSUE #263: [epoch processing] Implement `process_historical_summaries_update`
https://github.com/lambdaclass/lambda_ethereum_consensus/blob/66059de3653c17ae620ce2aca2db61c558057f6a/docs/specs/beacon-chain.md?plain=1#L2573-L2583

See Spec tests format: https://github.com/ethereum/consensus-specs/tree/dev/tests/formats/epoch_processing

Acceptance criteria:
- Run corresponding spec tests by removing https://github.com/lambdaclass/lambda_ethereum_consensus/blob/66059de3653c17ae620ce2aca2db61c558057f6a/test/spec/runners/epoch_processing.ex#L20

### PR DESCRIPTION
**Pull request by phklive**
**Motivation**

Core function of the epoch processing

Closes #263

### CODE REVIEW

**Comment by MegaRedHand** [comment]
My guess is that the SSZ NIF doesn't have enough information to process the call. The arguments are a list of binaries and a max size, but those binaries could mean anything. To hash lists of non-structs, you should use `hash_list_tree_root_typed/3`.

**Comment by phklive** [comment]
> My guess is that the SSZ NIF doesn't have enough information to process the call. The arguments are a list of binaries and a max size, but those binaries could mean anything. To hash lists of non-structs, you should use `hash_list_tree_root_typed/3`.

I am not sure what SszType to pass then considering that they are a `list(SszTypes.root())`

**Comment by MegaRedHand** [comment]
As discussed in the daily: we need to add the type implementation to the NIF. Basically:
1. Add a `SszTypes.Root` module (like `SszTypes.Transaction`)
2. Add the type in the Rust side (should work just adding the existing `Root` type to the macro in `utils/mod.rs`)

**Comment by phklive** [comment]
@MegaRedHand if you could give a quick look into my code:

These are my generated roots: 
SCR-20231018-ojpl

These are the required (post state) roots: 
SCR-20231018-ojui

I looked into my code and can't seem to find the error that makes the roots different.

**Comment by MegaRedHand** [comment]
Continued in #370

**Pull request closed without merging**
