### PR TITLE
feat: app OpenApiSpex

### LINKED ISSUE #165: Add OpenApiSpex to the phoenix endpoints
The [OpenApiSpex](https://github.com/open-api-spex/open_api_spex) projects allows for input validation using open api schemas that describe the fields and types we accept as part of a query. This issue will be considered finished once all implemented endpoints use Open API spex. After this issue is finished, all new endpoints should validate inputs with OpenApiSpex.

### PR DESCRIPTION
**Pull request by okekefrancis112**
**Motivation**

This pull request exists to add OpenApiSpex validations to the controllers.

**Description**

The OpenApiSpex validation was added to both the v1 and v2 Beacon controllers and also the pipeline on the router.

Closes #165

### CODE REVIEW

**Review by MegaRedHand — COMMENTED** [review]
Thanks for taking this on! Please sync with _main_ to simplify the file changes.

**Comment by okekefrancis112** [comment]
main synced

**Review by MegaRedHand — COMMENTED** [review]
I'm seeing a lot of unrelated changes in the readme. Also, files `libp2p_port/internal/proto/libp2p.pb.go` and `libp2p_port/libp2p_port` should be removed.

**Comment by mpaulucci** [comment]
Hi @okekefrancis112 , do you plan on keep on working on this one?

**Comment by okekefrancis112** [comment]
Hi Martin,

Yes please, I'd like to round up on this.
Please give me till Monday.

Warmly,
Okeke Francis

**Comment by MegaRedHand** [comment]
Continued in #456

**Pull request closed without merging**
