### PR TITLE
fix: refactor and file renaming

### LINKED ISSUE #632: [Refactor] Rename `mod.ex` to `base.ex`
We have a file for base types. We should:

1. Rename the file from `mod.ex` to `base.ex`
2. Rename the module from `Types` to `LambdaEthereumConsensus.Types.Base`. 
3. Use aliases in files where it's used.

### PR DESCRIPTION
**Pull request by mahmudsudo**
**Description**

refactorisation of module naming and renaming of files

#632 

Closes #632

### CODE REVIEW

**Comment by mahmudsudo** [comment]
@mpaulucci

**Review by Arkenan — CHANGES_REQUESTED** [review]
Hi @mahmudsudo ! Thanks for the PR. I just ran the CI jobs and some of the checks are not passing. Notably, the linter one. I notice that you removed most of the indents before the aliases, for instance. I recommend using a formatter in your IDE/code editor so that it auto formats on save. If not, running `mix format` from the terminal should solve this issues.

You can check that the format is correct in your own computer by running `make lint` and checking there are no warnings. 

Please fix this, get the updates from the main branch and request a review again afterwards.

**Comment by mahmudsudo** [comment]
@Arkenan

**Comment by Arkenan** [comment]
Hi @mahmudsudo 

Thanks for the new commit. I ran the CI and the linter is still not passing here on github. I git-fetched the changes from your head locally and when running `make lint`, I got the following errors:

```
 File: lib/lambda_ethereum_consensus/state_transition/accessors.ex 
[AliasOrder 10/3] The alias `LambdaEthereumConsensus.Utils` is not alphabetically ordered among its group
[AliasOrder 11/3] The alias `LambdaEthereumConsensus.Utils.BitList` is not alphabetically ordered among its group
[AliasOrder 12/3] The alias `LambdaEthereumConsensus.Utils.Randao` is not alphabetically ordered among its group

 File: lib/lambda_ethereum_consensus/validator/duties.ex 
[Format -/-] The file is not formatted.

 File: lib/lambda_ethereum_consensus/validator/validator.ex 
[Format -/-] The file is not formatted.

 File: lib/libp2p_port.ex 
[AliasOrder 18/3] The alias `LambdaEthereumConsensus.Types.Base.EnrForkId` is not alphabetically ordered among its group

 File: lib/types/state_info.ex 
[Format -/-] The file is not formatted.

 File: test/spec/runners/helpers/process_blocks.ex 
[AliasOrder 9/3] The alias `LambdaEthereumConsensus.Utils.Diff` is not alphabetically ordered among its group

 File: test/unit/req_resp_test.exs 
[Format -/-] The file is not formatted.
```

Have you tried running `make lint` in your computer? That would help you catch these errors without needing to run CI (which needs to be activated by a reviewer like me). I'm also pretty sure these can all be corrected by running `mix format` locally. Please run that, make sure the linter check passes on your computer before committing again.

**Comment by Arkenan** [comment]
Closing for inactivity + CI not passing

**Pull request closed without merging**
