### PR TITLE
feat: add `Metadata` SSZ container + unit test

### LINKED ISSUE #191: Add `Metadata` SSZ container
See: [the NIF's README](https://github.com/lambdaclass/lambda_ethereum_consensus/blob/main/native/ssz_nif/README.md) and [this PR](https://github.com/lambdaclass/lambda_ethereum_consensus/pull/188)

**MetaData**
```
(
  seq_number: uint64
  attnets: Bitvector[ATTESTATION_SUBNET_COUNT]
  syncnets: Bitvector[SYNC_COMMITTEE_SUBNET_COUNT]
)
```

### PR DESCRIPTION
**Pull request by namn-grg**
**Motivation**
Add `Metadata` SSZ container + unit test

**Description**

Closes #191

### CODE REVIEW

**Review by MegaRedHand — APPROVED** [review]
Please format the code with `mix format`. Apart from that, PR looks good 🔥

**Comment by namn-grg** [comment]
Done @MegaRedHand

**Comment by namn-grg** [comment]
Done @mpaulucci

**Comment by MegaRedHand** [comment]
@all-contributors please add @namn-grg for code

**Pull request merged**
