### PR TITLE
feat: merklelization of vector of composite objects

### LINKED ISSUE #679: [SSZ] Support for merklelization of vector of composite objects

### PR DESCRIPTION
**Pull request by Godspower-Eze**
Closes #679

### CODE REVIEW

**Comment by MegaRedHand** [comment]
Is this a duplicate from #703 ?

**Comment by Godspower-Eze** [comment]
> Is this a duplicate of #703 ?

No. It builds on top of it

**Comment by MegaRedHand** [comment]
There seem to be no changes?

**Comment by Godspower-Eze** [comment]
> There seem to be no changes?

Yeah, been merging with #678

**Pull request closed without merging**
